/**
 * GENERATED from @tikz-editor/lezer-tikz/src/grammar/tikz.grammar.
 * Run scripts/generate-tikz-command-catalogue.mjs after updating the parser.
 */
export const TIKZ_CONTROL_WORDS = [
  "\\begin",
  "\\clip",
  "\\colorlet",
  "\\coordinate",
  "\\DeclareMathOperator",
  "\\DeclareRobustCommand",
  "\\def",
  "\\definecolor",
  "\\draw",
  "\\end",
  "\\fill",
  "\\filldraw",
  "\\footnotesize",
  "\\foreach",
  "\\graph",
  "\\huge",
  "\\Huge",
  "\\large",
  "\\Large",
  "\\LARGE",
  "\\let",
  "\\matrix",
  "\\newcommand",
  "\\node",
  "\\normalsize",
  "\\path",
  "\\pattern",
  "\\pgfkeys",
  "\\pic",
  "\\providecommand",
  "\\renewcommand",
  "\\scriptsize",
  "\\shade",
  "\\shadedraw",
  "\\small",
  "\\tikz",
  "\\tikzset",
  "\\tikzstyle",
  "\\tiny",
  "\\useasboundingbox",
  "\\usetikzlibrary"
] as const
